[program:ide-kasmvnc]
command=bash /app/supervisor/start.d/02-ide-kasmvnc.sh
user=root
autostart=true
startretries=3
autorestart=true
startsecs=0
priority=2
stdout_logfile=/app/logs/ide-kasmvnc.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/ide-kasmvnc.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
