[program:ccswitch-openbox]
command=bash /app/supervisor/start.d/02-ccswitch-openbox.sh
user=root
autostart=true
startretries=3
autorestart=true
priority=3
stdout_logfile=/app/logs/ccswitch-openbox.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/ccswitch-openbox.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
