[program:yprompt]
command=bash /app/supervisor/start.d/17-yprompt.sh
user=root
autostart=true
startretries=3
autorestart=true
exitcodes=0
startsecs=0
priority=16
stdout_logfile=/app/logs/yprompt.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/yprompt.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
