[program:npc]
command=bash /app/supervisor/start.d/19-npc.sh
user=root
autostart=true
startretries=3
autorestart=true
exitcodes=0
startsecs=0
priority=8
stdout_logfile=/app/logs/npc.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=/app/logs/npc.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
